### ISSUE TITLE
Reference files should not be listed in overview.html 

### ISSUE THREAD

**Issue by tstephen** [bpmn-miwg/bpmn-miwg-tools#16]
Example file attached. 
[overview.html.txt](https://github.com/bpmn-miwg/bpmn-miwg-tools/files/3149/overview.html.txt)

**Comment by falko** [comment]
@tstephen needs to take out the test and then the issue will be closed with no change.

**Comment by tstephen** [comment]
Backed out test.

**Comment by falko** [comment]
Thank you!
