### ISSUE TITLE
Missing file submissions.json

### ISSUE THREAD

**Issue by tstephen** [bpmn-miwg/bpmn-miwg-tools#19]
After compiling v0.3 HEAD and following the deployment instructions [here](https://github.com/bpmn-miwg/bpmn-miwg-tools) I found that a file 'submissions.json' is expected but not present.

**Comment by falko** [comment]
This file is produced by me, using the submission counter that I wrote. 
However, I didn't properly integrate it into the tool suite yet. Sorry 
for that. For the moment just use the file from GitHub: 
http://bpmn-miwg.github.io/bpmn-miwg-tools/submissions.json

**Comment by SimonRinguette** [comment]
The table is currently not loading at http://bpmn-miwg.github.io/bpmn-miwg-tools/ complaining that it does not find submissions.json

**Comment by tstephen** [comment]
I've restored the last committed file but it now complains: Uncaught TypeError: Cannot read property 'count' of undefined
