### ISSUE TITLE
Generated bounds images are gone from the repo

### ISSUE THREAD

**Issue by barmac** [bpmn-miwg/bpmn-miwg-tools#46]
In 0340461d00239e823eeedbf15e35e90312624116, all of the generated bounds overlays were removed from the `gh-pages` branch. This is the exact commit which introduced the issue that we cannot compare bounds on the results page.

@tstephen @falko

**Comment by tstephen** [comment]
Resolved by https://github.com/bpmn-miwg/bpmn-miwg-test-suite/commit/0a694c97c9678e517ab0192a21d4e5a02a29e2f0
