### ISSUE TITLE
XPath compare tools does not properly check the files against the XSD

### ISSUE THREAD

**Issue by SimonRinguette** [bpmn-miwg/bpmn-miwg-tools#8]
I think that there may be something wrong with the XSD validation in the XPath tool. 

For instance, the B.1.0 roundtrip result provided by Signavio has an XSD validation issue in the ordering of the process elements for process id=WFP-6-2:

      <dataObject id="sid-bb8b69f0-e820-4500-a083-56d75b68321f" isCollection="false" name="Data Object"/>
      <laneSet id="sid-93838460-23ff-41a9-a552-87ca31b40417">

The XSD Schema requires lanesets to be defined before flowElements (like dataObject).

      <xsd:element ref="laneSet" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element ref="flowElement" minOccurs="0" maxOccurs="unbounded"/>

This type of error also occurs on other vendors.

**Comment by falko** [comment]
Fixed by additional schema validation tool.
